server:
  port: 17808
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/buywhat?serverTimezone=GMT
    username: root
    password: 666888
    driver-class-name: com.mysql.cj.jdbc.Driver
  velocity:
     suffix: .html
     toolbox-config-location: datetool.xml

#  mvc:
#    view:
#      prefix: WEB-INF/jsp/
#      suffix: .jsp